# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_num', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('total_worker_count', models.IntegerField(blank=True, null=True)),
                ('total_patient_count', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'emergency',
            },
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('nurse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Department')),
            ],
            options={
                'db_table': 'nurses',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('dt_birth', models.DateField(blank=True, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.Patient')),
                ('date_admission', models.DateField()),
                ('date_discharge', models.DateField(blank=True, null=True)),
                ('prescription', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Department')),
            ],
            options={
                'db_table': 'admitted',
            },
        ),
        migrations.CreateModel(
            name='WorksFor',
            fields=[
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.Doctors')),
                ('schedule', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Department')),
            ],
            options={
                'db_table': 'works_for',
            },
        ),
        migrations.AddField(
            model_name='emergency',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Doctors'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Nurses'),
        ),
        migrations.AlterUniqueTogether(
            name='nurses',
            unique_together=set([('department', 'nurse_id')]),
        ),
        migrations.AddField(
            model_name='admitted',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Doctors'),
        ),
        migrations.AlterUniqueTogether(
            name='worksfor',
            unique_together=set([('department', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='admitted',
            unique_together=set([('patient', 'department', 'date_admission')]),
        ),
    ]
