# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20181021_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_num', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
                ('total_worker_count', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('dt_birth', models.DateField(blank=True, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.Patient')),
                ('date_admission', models.DateField()),
                ('date_discharge', models.DateField(blank=True, null=True)),
                ('prescription', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_grade', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'admitted',
            },
        ),
        migrations.CreateModel(
            name='WorksFor',
            fields=[
                ('department_num', models.ForeignKey(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.Department')),
                ('schedule', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Doctors')),
            ],
            options={
                'db_table': 'works_for',
            },
        ),
        migrations.AddField(
            model_name='admitted',
            name='department_num',
            field=models.ForeignKey(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Department'),
        ),
        migrations.AddField(
            model_name='admitted',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Doctors'),
        ),
        migrations.AlterUniqueTogether(
            name='worksfor',
            unique_together=set([('department_num', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='admitted',
            unique_together=set([('patient', 'department_num', 'date_admission')]),
        ),
    ]
