# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20181025_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksfor',
            name='department_num',
            field=models.ForeignKey(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Department'),
        ),
        migrations.AlterField(
            model_name='worksfor',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.Doctors'),
        ),
    ]
