# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20181118_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='total_patient_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
