# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_department_total_patient_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitted',
            name='doctor_grade',
        ),
    ]
