# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_admitted_doctor_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admitted',
            old_name='department_num',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='department_num',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='worksfor',
            old_name='department_num',
            new_name='department',
        ),
        migrations.AlterUniqueTogether(
            name='admitted',
            unique_together=set([('patient', 'department', 'date_admission')]),
        ),
        migrations.AlterUniqueTogether(
            name='nurses',
            unique_together=set([('department', 'nurse_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='worksfor',
            unique_together=set([('department', 'employee')]),
        ),
    ]
