# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20181124_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
