# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20181126_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
